# 服务端口
server:
  port: 5000
  servlet:
    context-path: /azir

# 数据源配置
datasource:
  mysql:
    url: jdbc:mysql://127.0.0.1:3306/azir
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver